[package]
name = "simple_rest_api"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]

[dependencies]
hyper = "0.12"
futures = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
diesel = { version = "1.3.2", features = ["postgres"] }
dotenv = "0.9.0"

