-- Your SQL goes here
CREATE TABLE readings (
  id SERIAL PRIMARY KEY,
  timestamp DOUBLE PRECISION NOT NULL,
  x DOUBLE PRECISION NOT NULL,
  y DOUBLE PRECISION NOT NULL,
  z DOUBLE PRECISION NOT NULL
)
